web:
  image: niklongstone/learning-php7:1.0
  ports:
    - "80:80"
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: mydb
